[project]
name = 'zest-sbtc'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.bridge-endpoint]
path = 'contracts/bridge-endpoint.clar'
clarity_version = 2
epoch = 2.5

[contracts.btc-bridge-registry-v1-01]
path = 'contracts/btc-bridge-registry-v1-01.clar'
clarity_version = 2
epoch = 2.5

[contracts.btc-data]
path = 'contracts/btc-data.clar'
clarity_version = 2
epoch = 2.5

[contracts.clarity-bitcoin-v1-02]
path = 'contracts/clarity-bitcoin-v1-02.clar'
clarity_version = 2
epoch = 2.5

[contracts.stacking-btc]
path = 'contracts/stacking-btc.clar'
clarity_version = 2
epoch = 2.5

[contracts.stacking-data]
path = 'contracts/stacking-data.clar'
clarity_version = 2
epoch = 2.5

[contracts.token-btc]
path = 'contracts/token-btc.clar'
clarity_version = 2
epoch = 2.5

[contracts.trait-sip-010]
path = 'contracts/trait-sip-010.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
